### ISSUE TITLE
how do i download and install it

### ISSUE THREAD

**Issue by inikishev** [CamperSamu/WhereAreYouFrom#11]
i downloaded the latest version but is it for 1.20.1? and I downloaded the one that doesnt say -sources. but it crashes on startup. Is this forge or fabric? https://gist.github.com/stunlocked1/e2f82949f6938ef11e9e1ca604fa41b0

**Comment by CamperSamu** [comment]
I marked my mod as 1.20.1 compatible by mistake (Modrinth autoselected the version and I forgot to change `1.20.x` to `>=1.20.3` inside the mod json.

I am planning to make my mods cross-version but as of right now the mod isn't available for 1.20.1.
