### ISSUE TITLE
It counts for "Minecraft" too?

### ISSUE THREAD

**Issue by sternschnaube** [CamperSamu/WhereAreYouFrom#9]
I was checking all items and see the Minecraft tag now.

![image](https://github.com/CamperSamu/WhereAreYouFrom/assets/120551916/ad3d2a0e-7b6a-46c7-b8e5-0ad9c7294246)

Instead of:

![image](https://github.com/CamperSamu/WhereAreYouFrom/assets/120551916/73a657db-1a0d-411f-b2d6-105debeb62dd)

Can this please be disabled? I know what's Vanilla, it takes unnecessary tooltip space and I don't want all items to be affected from this mod. The mod description was not pointing out that even Vanilla items are affected from it...

**Comment by CamperSamu** [comment]
> The mod description was not pointing out that even Vanilla items are affected from it

The mod actually kinda does (it says it replicates WAILA behavior, that is to tag all items) but sure, this can be added.

Also I noticed that you are using this mod in a clientside modpack, whilst this mod works clientside too, this mod is strictly designed for serverside use only.
I suggest using REI/JEI/EMI or Jade/WTHIT (WAILA) instead.

**Comment by venaminecraft** [comment]
A config option to disable the "Minecraft" tag / for Vanilla items sounds great 😊

I have the mod just on the server-side 🤔
And I'm also only play on server 😄
(I don't think I was putting it on the client side too, but can't check right now.)

**Comment by CamperSamu** [comment]
> I have the mod just on the server-side 🤔

Ah ok, but is it a modded server with a clientside modpack?
Because I see the AE2/TSS UI for items (search bar + 77k stone)

If the server and client share the same modpack, I suggest using something like [Jade](https://modrinth.com/mod/jade) instead.

**Comment by venaminecraft** [comment]
It comes from Chest Tracker: https://modrinth.com/mod/chest-tracker

My focus is mainly on Vanilla, everything server-side and no Client force mods.

I like your mod because of Jump Vadder: https://modrinth.com/mod/jumpvader

It's awesome to see that it comes from Polymer.

**Comment by CamperSamu** [comment]
> It comes from Chest Tracker: https://modrinth.com/mod/chest-tracker

Ohh I see, I completely forgot about that mod somehow!
I just pushed your suggestion (d6c0be32b63e505729633da288b3248685812370) and I took the opportunity to work on another feature too in the meantime (4830232c23ddc189a6f9928301a3fe3a96052a34)

Marking the issue as completed, releasing the update in a bit!

**Comment by CamperSamu** [comment]
You will see two new files popping out in your `config` folder:
- `wayf.flags`
  - This contains your requested feature, aka the switch for disabling the "Minecraft" & "Unknown" tooltip (+ renaming the "Unknown" tooltip to something else)
- `wayf.ignore`
  - This allows you to disable the mod if the item lore contains a specific word; this is useful for compatability with datapacks such as Incendium or Stellarity.
  - To disable this feature, go to `wayf.flags` and set `ignoreListEnabled` to `false`.

**Comment by CamperSamu** [comment]
Update released: https://modrinth.com/mod/shoutout/version/1.4.0

**Comment by venaminecraft** [comment]
That was fast - thanks a lot ☺️
